model: exp/USPTO_full_RtoP_aug5_backT/finetune_average_model_v2_46-50.pt
#src: dataset/USPTO_extra_RtoP_aug5_seed32/train/src-train.txt
src: dataset/USPTO_extra_full_PtoR_aug5_seed33/train/tgt-train.txt
#output: exp/USPTO_extra_full_raw_bt/backT_full_46-50-results_best1_seed32.txt
output: exp/USPTO_extra_full_raw_bt/backT_extra-full_46-50-results_v2.txt
gpu: 2
beam_size: 50
n_best: 1
batch_size: 2048
batch_type: tokens
max_length: 1000
seed: 0
#log_file: log/USPTO_extra_full_raw_bt/finetune_model_product-reactants-translate_46-50-best1_seed32.log
