model: exp/USPTO-MIT_RtoP_aug5_mixed/finetuned_average_model_46-50.pt
src: dataset/USPTO_extra_mit_PtoR_aug5_seed33/train/tgt-train.txt
output: exp/USPTO_extra-mit_MIT_raw_bt/backT_MIT_46-50-results_beam50.txt
gpu: 3
beam_size: 50
n_best: 1
batch_size: 4096
batch_type: tokens
max_length: 1000
seed: 0
