data:
  corpus_1:
    path_src: dataset/USPTO_50K_RtoP_aug20_backT/train/src-train.txt
    path_tgt: dataset/USPTO_50K_RtoP_aug20_backT/train/tgt-train.txt
  valid:
    path_src: dataset/USPTO_50K_RtoP_aug20_backT/val/src-val.txt
    path_tgt: dataset/USPTO_50K_RtoP_aug20_backT/val/tgt-val.txt

n_sample: 0
save_data: dataset/USPTO_full_pretrain_aug5_product_masked_token/example
src_vocab: dataset/USPTO_full_pretrain_aug5_product_masked_token/example.vocab.src
tgt_vocab: dataset/USPTO_full_pretrain_aug5_product_masked_token/example.vocab.src
share_vocab: 'true'
src_seq_length: 500
tgt_seq_length: 500
overwrite: 'true'

train_from: exp/USPTO_full_pretrain_aug5_product_masked_token/pretrain_model_step_1000000.pt
reset_optim: 'all'
save_model: exp/USPTO_50K_RtoP_aug20/finetune_model.product-reactants
save_checkpoint_steps: 10000
keep_checkpoint: 5
seed: 3435
train_steps: 300000
valid_steps: 100000
warmup_steps: 8000
report_every: 1000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
rnn_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 1.0
max_grad_norm: 0.0

batch_size: 9000
valid_batch_size: 9000
batch_type: tokens
normalization: tokens
dropout: 0.1
attention_dropout: 0.3
label_smoothing: 0.0

max_generator_batches: 0

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 3
gpu_ranks: [0,1,2]
log_file: log/USPTO_50K_RtoP_aug20/finetune_model_product-reactants.log
