model: exp/USPTO_extra_50K_PtoR_raw_bt/finetune_average_model_36-40-batch9k-extra-filter5-fp0.55-fullfill.pt
src: dataset/USPTO_50K_PtoR_aug20/test/src-test.txt
output: exp/USPTO_extra_50K_PtoR_raw_bt/finetune_average_model_36-40-results-batch9k-extra-filter5-fp0.55-fullfill.txt
gpu: 7
beam_size: 50
n_best: 50
batch_size: 4096
batch_type: tokens
max_length: 500
seed: 0
