data:
  corpus_1:
    path_src: dataset/USPTO_50K_PtoR_aug20/train/src-train.txt
    path_tgt: dataset/USPTO_50K_PtoR_aug20/train/tgt-train.txt
    weight: 5
 corpus_3:
    path_src: dataset/USPTO_extra_RtoP_aug5/train/filter-5/0.55/tgt-train_r.txt
    path_tgt: dataset/USPTO_extra_RtoP_aug5/train/filter-5/0.55/src-train_r.txt
    weight: 5
  valid:
    path_src: dataset/USPTO_50K_PtoR_aug20/val/src-val.txt
    path_tgt: dataset/USPTO_50K_PtoR_aug20/val/tgt-val.txt

n_sample: 0
save_data: dataset/USPTO_full_pretrain_aug5_product_masked_token/example
src_vocab: dataset/USPTO_full_pretrain_aug5_product_masked_token/example.vocab.src
tgt_vocab: dataset/USPTO_full_pretrain_aug5_product_masked_token/example.vocab.src
share_vocab: 'true'
src_seq_length: 500
tgt_seq_length: 500
overwrite: 'true'

train_from: exp/USPTO_full_pretrain_aug5_product_masked_token/pretrain_model_step_1000000.pt
reset_optim: 'all'
save_model: exp/USPTO_extra_50K_PtoR_raw_bt/finetune_model.product-reactants-batch9k-extra-filter5-fp0.55-fullfill
save_checkpoint_steps: 10000
keep_checkpoint: 5
seed: 3435
train_steps: 400000
valid_steps: 100000
warmup_steps: 8000
report_every: 1000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
rnn_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 1.0
max_grad_norm: 0.0

batch_size: 8192
batch_type: tokens
valid_batch_size: 8192
normalization: tokens
dropout: 0.1
attention_dropout: 0.1
label_smoothing: 0.0

max_generator_batches: 32

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 2
gpu_ranks: [0,1]
master_port: 12323
log_file: log/USPTO_extra_50K_PtoR_raw_bt/finetune_model_product-reactants-batch9k-extra-filter5-fp0.55-fullfill
